### ISSUE TITLE
Distribution Rights

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.WinSCP#1]
Just had a quick look at the NuGet package for Cake.WinSCP and I see that you are including the WinSCP.exe.  Do you have distribution rights for doing this?  Have you checked the license associated with the package?

**Comment by ilich** [comment]
Well, it is distributed under GPLv3. This is from the official website (https://winscp.net/eng/docs/license):

No matter if you are an individual, or representative of educational institution, small firm or corporation, the GPL license grants you following rights:
1. Run WinSCP for any purpose for free;
2. Copy WinSCP anywhere you want in any number of copies or Provide a download link on your website;
3. Make whatever modifications to WinSCP you want (though your modification must also be released under the GPL).

Actually, WinSCP.exe is coming with .NET API. .NET API is a wrapper around WinSCP scripting language.

Do you see any legal issue here?

**Comment by gep13** [comment]
Nope, that's perfect. Just wanted to check that it had been thought about. :smile:
