### ISSUE TITLE
Current working directory

### ISSUE THREAD

**Issue by dracan** [cake-contrib/Cake.WinSCP#2]
Very useful - thanks for creating this :) One issue I've noticed is that the current directory seems to be that of the winscp.exe, rather than where the task itself is running from. This means that if you set the `localFolder` parameter to something relative, it doesn't work.

**Comment by dracan** [comment]
It's actually very easy to get around ...

    WinScpSync(ftpUri,
               "/site/wwwroot",
               MakeAbsolute(new DirectoryPath(".")).ToString(),
               false);

But cleaner if that argument could just be "" or "."

**Comment by ilich** [comment]
Thank you for the feedback!

I have added WinSCP local folder to support. You should be able to use relative path now.

**Comment by dracan** [comment]
Wow - that was quick! Good work, and thanks for that :)
