### ISSUE TITLE
Error creating folder (Error code 4) when syncing

### ISSUE THREAD

**Issue by mennowo** [cake-contrib/Cake.WinSCP#9]
When using WinScpSync, if a given folder already exists remotely, an error occurs (WinSCP error code 4).

## Expected Behavior
Sync remote data with data locally.

## Current Behavior
Works the first time, then causes an error.

## Possible Solution
Deleting the remote folder before sync? Although that would not really be syncing.

## Steps to Reproduce (for bugs)
Call WinScpSync once for a folder that does exist remotely, then again.

## Context
After building, I'd like to transfer some artifacts via sftp.

## Your Environment
* Addin version used: 0.4.1
* Cake Version used: 0.36.0
* Operating System: Win10 x64

**Comment by mennowo** [comment]
In the mean time I was able to achieve a similar result using the info here: https://www.phillipsj.net/posts/cake-more-sftp/

Note that in the session.PutFiles() method, one has to use backslashes for the local folder on Windows. In ended up with:

```
outputDir.Path.MakeAbsolute(Context.Environment).ToString().Replace("/", "\\")
```

**Comment by igloo15** [comment]
@mennowo can you tell me which function you used and what arguments you passed to it so I can test this.

This library is mostly just a wrapper around WinSCP library. The default settings for WinScpSync function are the following:

- RemoveFiles: False
- SynchronizationMode: Remote
- Mirror Mode: false,
- SynchronizationCriteria: Time
- TransferOptions: empty/null

So I would read up on WinSCP and determine what the appropriate settings should be to do what you need to do. Reviewing the code of this library we do not do anything special beyond forward your stuff to the WinScp Library. 

If this is truly a bug you may want to look at reporting to [WinSCP Library](https://github.com/winscp/winscp)
